import os

# Get the root path of the project
ROOT_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) 

MESSAGES = {
    "zh-CN": {
        "start": "已启动",
        "error": "出现了一个错误：",
        "thinking": "思考中",
        "func_error": "没有开发{func_name}这个功能",
        "exit": "正在关闭",
        "reboot": "正在重启",
        "command_error": "命令执行失败：",
        "evaluate_error": "计算失败：",
        "execute_success": "执行成功\n",
        "execute_failed": "执行失败：",
        "time_word": "今天是",
        "parallel_word": "\n当前为并行模式，请仅将此复杂任务拆分并完成第一步。当前并行数为{parallel}，你的编号为{n_tb}",
        "continue_word": "请继续回答，但不要说任何类似“好的”的话",
        "no_chat_model": "没有此聊天模型",
        "mdcb_no_return": "mdcb无返回",
        "history_clean": "聊天记录清理成功",
        "history_save": "聊天记录保存成功",
        "email_send_success": "邮件发送成功",
        "set_success": "已将{setting}设置为{value}",
        "set_failed": "{setting}设置失败",
        "no_setting_option": "没有{setting}这个设置选项，请咨询{bot_name}",
        "add_alarm_failed": "添加闹钟失败，无法将{time_data}识别为一个时间",
        "add_alarm_success": "已添加{time_str}的{info}闹钟",
        "add_alarm_exist": "添加闹钟失败，已经有 {time_str} 这个时间的闹钟了",
        "cancel_alarm_failed": "取消闹钟失败，无法将{time_data}识别为一个时间",
        "cancel_alarm_success": "已取消{time_str}的{info}闹钟",
        "cancel_alarm_exist": "取消闹钟失败，没有{time_str}这个时间的闹钟",
        "alarm_get": "当前共有以下闹钟：\n{alarm_result}",
        "alarm_get_none": "当前没有闹钟",
        "file_check_success": "存在这个文件：{file}",
        "file_check_folder": "该地址为一个文件夹，其中的文件/文件夹为：\n{file_text}",
        "file_check_failed": "不存在这个文件/文件夹",
        "file_read_failed": "文件读取失败，文件不存在",
        "weather_forcast": "{country} {region} {city} 接下来{days}天的天气为：\n",
        "weather_day": "{date}，{condition}，最高温度：{max_temp}°C，最低温度：{min_temp}°C，湿度：{humidity}%\n",
        "weather_get_failed": "天气获取失败",
        "wiki_search": "搜索到{wiki_search[0]}的内容如下：\n{result}",
    },
    "en-US": {
        "start": "has started",
        "error": "There is an error occurred: ",
        "thinking": "is thinking",
        "func_error": "The function {func_name} has not been developed.",
        "exit": "is closing",
        "reboot": "is rebooting",
        "command_error": "Command execution failed: ",
        "evaluate_error": "Evaluation failed: ",
        "execute_success": "Execution successful\n",
        "execute_failed": "Execution failed: ",
        "time_word": "Today is ",
        "parallel_word": "\nThe current mode is parallel processing. Please only split this complex task and complete the first step. The current parallel count is {parallel}, and your ID is {n_tb}.",
        "continue_word": "Please continue answering directly without saying anything like 'Okay' or 'All right'.",
        "no_chat_model": "No such chat model",
        "mdcb_no_return": "mdcb returns nothing",
        "history_clean": "Chat history cleared successfully",
        "history_save": "Chat history saved successfully",
        "email_send_success": "Email sent successfully",
        "set_success": "{setting} has successfully set to {value}",
        "set_failed": "Failed to set {setting}",
        "no_setting_option": "No setting option named {setting}, please consult {bot_name}",
        "add_alarm_failed": "Failed to add alarm, cannot recognize {time_data} as a time",
        "add_alarm_success": "{info} alarm added successfully at {time_str}",
        "add_alarm_exist": "Failed to add alarm, there is already an alarm set for {time_str}",
        "cancel_alarm_failed": "Failed to cancel alarm, cannot recognize {time_data} as a time",
        "cancel_alarm_success": "The {info} alarm calcelled successfully at {time_str}",
        "cancel_alarm_exist": "Failed to cancel alarm, there is no alarm set for {time_str}",
        "alarm_get": "The current alarm(s) are as follows: \n{alarm_result}",
        "alarm_get_none": "There are currently no alarms.",
        "file_check_success": "The file exists: {file}",
        "file_check_folder": "The address is a folder, the files/folders within are: \n{file_text}",
        "file_check_failed": "There is no such file/folder",
        "file_read_failed": "File reading failed, the file does not exist",
        "weather_forcast": "Weather forecast for {city} {region} {country} in the next {days} day(s):\n",
        "weather_day": "{date}, {condition}, Max temperature: {max_temp}°C, Min temperature: {min_temp}°C, Humidity: {humidity}%\n",
        "weather_get_failed": "Error: Cannot fetch weather forecast",
        "wiki_search": "The content found for {wiki_search[0]} is as follows:\n{result}",
    }
}